openapi: 3.0.0
info:
  title: Google Sheets Proxy API
  version: 1.0.0
  description: Minimal proxy that adds OAuth token to Google Sheets API requests

servers:
  - url: https://your-deployment.vercel.app

paths:
  /api/proxy:
    post:
      operationId: sheetsProxy
      summary: Proxy requests to Google Sheets API
      description: Forwards requests to any Google Sheets API endpoint with OAuth authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - endpoint
              properties:
                endpoint:
                  type: string
                  description: The Google Sheets API endpoint path (without base URL)
                  example: "spreadsheets/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/values/Sheet1!A1:append?valueInputOption=USER_ENTERED"
                method:
                  type: string
                  description: HTTP method (defaults to POST)
                  enum: [GET, POST, PUT, DELETE]
                  default: POST
              additionalProperties: true
              example:
                endpoint: "spreadsheets/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/values/Sheet1!A1:append?valueInputOption=USER_ENTERED"
                method: "POST"
                values: [["Data 1", "Data 2", "Data 3"]]
      responses:
        '200':
          description: Response from Google Sheets API
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad request - missing endpoint
        '401':
          description: Unauthorized
        '405':
          description: Method not allowed
